DATASET: spacenet
NO_SAM: false
SAM_VERSION: vit_b
SAM_CKPT_PATH: sam_ckpts/sam_vit_b_01ec64.pth
PATCH_SIZE: 256
BATCH_SIZE: 64
DATA_WORKER_NUM: 4
TRAIN_EPOCHS: 30
BASE_LR: 0.001
FREEZE_ENCODER: false
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: false
FOCAL_LOSS: false
USE_SAM_DECODER: false
TOPO_SAMPLE_NUM: 128
TOPONET_VERSION: normal
INFER_BATCH_SIZE: 64
SAMPLE_MARGIN: 0
INFER_PATCHES_PER_EDGE: 16
ITSC_THRESHOLD: 0.195
ROAD_THRESHOLD: 0.341
TOPO_THRESHOLD: 0.705
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16
USE_FPN: true
FPN_OUT_DIM: 256
USE_CNN_STEM: true
STAGE_D_PHASE1_USE_P4_ONLY: true
CNN_STEM_OUT_C3: 256
CNN_STEM_OUT_C4: 256
FUSE_TYPE: concat_1x1
FUSE_OUT_CHANNELS: 256
FUSE_USE_NORM: true
FPN_OUT_CHANNELS: 256
FREEZE_SAM_ENCODER: false
UNFREEZE_SAM_LAST_K: 0
