BASE_LR: 0.001
BATCH_SIZE: 64
CLDICE_ALPHA: 0.5
CLDICE_ITERS: 10
CLDICE_SMOOTH: 1.0
CLDICE_WEIGHT: 0.5
DATASET: spacenet
DATA_WORKER_NUM: 1
DEBUG_NAN: false
ENCODER_LORA: false
ENCODER_LR_FACTOR: 0.1
FOCAL_LOSS: false
FREEZE_ENCODER: false
INFER_BATCH_SIZE: 64
INFER_PATCHES_PER_EDGE: 16
ITSC_NMS_RADIUS: 8
ITSC_THRESHOLD: 0.195
MAX_NEIGHBOR_QUERIES: 16
NEIGHBOR_RADIUS: 64
NO_SAM: false
PATCH_SIZE: 256
ROAD_NMS_RADIUS: 16
ROAD_THRESHOLD: 0.341
SAMPLE_MARGIN: 0
SAM_CKPT_PATH: sam_ckpts/sam_vit_b_01ec64.pth
SAM_VERSION: vit_b
TOPONET_VERSION: normal
TOPO_SAMPLE_NUM: 128
TOPO_THRESHOLD: 0.705
TRAIN_EPOCHS: 30
USE_CLDICE: true
USE_SAM_DECODER: false
